/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        // Stitch design tokens
        primary:                   '#003c90',
        'on-primary':              '#ffffff',
        'primary-container':       '#0f52ba',
        'primary-fixed':           '#d9e2ff',
        'primary-fixed-dim':       '#b0c6ff',
        'on-primary-fixed':        '#001945',
        'on-primary-fixed-variant':'#00419c',
        secondary:                 '#006c49',
        'on-secondary':            '#ffffff',
        'secondary-container':     '#6cf8bb',
        'on-secondary-container':  '#00714d',
        background:                '#f8f9ff',
        'on-background':           '#0b1c30',
        surface:                   '#f8f9ff',
        'surface-bright':          '#f8f9ff',
        'surface-dim':             '#cbdbf5',
        'surface-container-lowest':'#ffffff',
        'surface-container-low':   '#eff4ff',
        'surface-container':       '#e5eeff',
        'surface-container-high':  '#dce9ff',
        'surface-container-highest':'#d3e4fe',
        'on-surface':              '#0b1c30',
        'on-surface-variant':      '#434653',
        'surface-variant':         '#d3e4fe',
        outline:                   '#737784',
        'outline-variant':         '#c3c6d5',
        error:                     '#ba1a1a',
        'on-error':                '#ffffff',
        'error-container':         '#ffdad6',
        'on-error-container':      '#93000a',
        'inverse-surface':         '#213145',
        'inverse-on-surface':      '#eaf1ff',
        'inverse-primary':         '#b0c6ff',

        // VaultShare theme-aware tokens
        'vs-bg':             'var(--vs-bg)',
        'vs-card':           'var(--vs-card)',
        'vs-heading':        'var(--vs-heading)',
        'vs-body':           'var(--vs-body)',
        'vs-muted':          'var(--vs-muted)',
        'vs-border':         'var(--vs-border)',
        'vs-border-subtle':  'var(--vs-border-subtle)',
        'vs-hover':          'var(--vs-hover)',
        'vs-surface':        'var(--vs-surface)',
        'vs-active':         'var(--vs-active)',
        'vs-brand':          'var(--vs-brand)',
        'vs-brand-text':     'var(--vs-brand-text)',
        'vs-brand-light':    'var(--vs-brand-light)',
        'vs-success':        'var(--vs-success)',
        'vs-success-surface':'var(--vs-success-surface)',
        'vs-error':          'var(--vs-error)',
        'vs-error-surface':  'var(--vs-error-surface)',
        'vs-warn':           'var(--vs-warn)',
        'vs-warn-surface':   'var(--vs-warn-surface)',
        'vs-avatar-bg':      'var(--vs-avatar-bg)',
        'vs-ring-white':     'var(--vs-ring-white)',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        display: ['Geist', 'Inter', 'sans-serif'],
      },
      animation: {
        spotlight: 'spotlight 2s ease .75s 1 forwards',
      },
      keyframes: {
        spotlight: {
          '0%':   { opacity: '0', transform: 'translate(-72%, -62%) scale(0.5)' },
          '100%': { opacity: '1', transform: 'translate(-50%, -40%) scale(1)' },
        },
      },
    },
  },
  plugins: [],
}
